# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edx < Formula
  desc "Edge Delta command-line interface"
  homepage "https://github.com/edgedelta/edx"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edgedelta/edx/releases/download/v0.8.0/edx_0.8.0_Darwin_x86_64.tar.gz"
      sha256 "b9449a742a38b989038d9fc8027cf8ab652ae2e0d576ed6bb20b611f9bb5a6f9"

      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edgedelta/edx/releases/download/v0.8.0/edx_0.8.0_Darwin_arm64.tar.gz"
      sha256 "b21c359d505f3ff4c54bbbeffe9a2054917dad6e13ce9602659e3d0228dafe0a"

      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.8.0/edx_0.8.0_Linux_x86_64.tar.gz"
      sha256 "5b2d9ad6dcb98bc4eb1414f7d36c70180674b7190f22137da76e62064a61198b"
      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.8.0/edx_0.8.0_Linux_arm64.tar.gz"
      sha256 "e84796ad080487036543a74866df155eab373461ab18b09e12b215bce45ca5fe"
      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  def caveats
    <<~EOS
      ▲ EDGE DELTA · edx

      Get started:
        edx auth login      # sign in (opens your browser)
        edx --help          # explore commands

      Docs: https://github.com/edgedelta/edx
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edx version")
  end
end
