# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edx < Formula
  desc "Edge Delta command-line interface"
  homepage "https://github.com/edgedelta/edx"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edgedelta/edx/releases/download/v0.5.0/edx_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "08827623358dab2d6437571e3e6335ce294330bf76b584ce230c01238d1ebbc8"

      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edgedelta/edx/releases/download/v0.5.0/edx_0.5.0_Darwin_arm64.tar.gz"
      sha256 "c5ae2cb60205ad51bf31c375d20e35a10aef456ba3dcc634301b13674d5e686a"

      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.5.0/edx_0.5.0_Linux_x86_64.tar.gz"
      sha256 "d71d507055b0629dd2bc9eada214e7264ef1dd28fc78d2cf5f9587441c04be60"
      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.5.0/edx_0.5.0_Linux_arm64.tar.gz"
      sha256 "7847914ee5c72184d291cebb82807d095b6228ae792098b7fb37cc80caea2884"
      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  def caveats
    <<~EOS
      ▲ EDGE DELTA · edx

      Get started:
        edx auth login      # sign in (opens your browser)
        edx --help          # explore commands

      Docs: https://github.com/edgedelta/edx
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edx version")
  end
end
