# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edx < Formula
  desc "Edge Delta command-line interface"
  homepage "https://github.com/edgedelta/edx"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edgedelta/edx/releases/download/v0.1.0/edx_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "1f7efb6164188c9eb78b0b83acf28ee18246b03b6945ce85fbab7f140a6b9dfe"

      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edgedelta/edx/releases/download/v0.1.0/edx_0.1.0_Darwin_arm64.tar.gz"
      sha256 "50fe0104071ed1f64376e9306d0980e568451f1804122c982aed743f80aa0818"

      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.1.0/edx_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a0d3bea09fe03665a170cd073e41787e44029db9d3d8e51d10ed1b95173e96d2"
      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.1.0/edx_0.1.0_Linux_arm64.tar.gz"
      sha256 "63176f850e3f3633abcf782e72ffb9bd92a117377f69afc1a7169835d59cae78"
      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edx version")
  end
end
